"use strict";
exports.__esModule = true;
var cliente_1 = require("./cliente");
var aviao_1 = require("./aviao");
var produtoEletronico_1 = require("./produtoEletronico");
var funcionario_1 = require("./funcionario");
var cliente = new cliente_1.Cliente('32d', 'Lucas', 30);
var aviao = new aviao_1.Aviao('Aviona', 345, 2014, 'TAM', 20);
var produtoEletronico = new produtoEletronico_1.ProdutoEletronico();
var funcionario = new funcionario_1.Funcionario("David", 30, "Amazon", 1200);
aviao.anoLancamento = 2014;
aviao.codigo = 214;
aviao.empresa = 'TAM';
aviao.modelo = 'Air5';
produtoEletronico.nome = 'ventilador';
produtoEletronico.empresa = 'MONDIAL';
produtoEletronico.preco = 120;
cliente.infosClient();
aviao.infosAviao(75);
console.log("Produto: ".concat(produtoEletronico.nome));
console.log("Empresa: ".concat(produtoEletronico.empresa));
console.log("Pre\u00E7o: ".concat((produtoEletronico.preco).toFixed(2)));
funcionario.depositar(300);
