"use strict";
exports.__esModule = true;
var cliente_1 = require("./cliente");
var aviao_1 = require("./aviao");
var produtoEletronico_1 = require("./produtoEletronico");
var funcionario_1 = require("./funcionario");
var cliente = new cliente_1.Cliente();
var aviao = new aviao_1.Aviao();
var produtoEletronico = new produtoEletronico_1.ProdutoEletronico();
var funcionario = new funcionario_1.Funcionario("David", 25, 'Amazon', 2600);
cliente.id = '1';
cliente.nome = 'Ricardo';
cliente.idade = 40;
aviao.anoLancamento = 2014;
aviao.codigo = 214;
aviao.empresa = 'TAM';
aviao.modelo = 'Air5';
produtoEletronico.nome = 'ventilador';
produtoEletronico.empresa = 'MONDIAL';
produtoEletronico.preco = 120;
funcionario.nome = 'David';
funcionario.idade = 27;
funcionario.empresa = 'Amazon';
console.log("Id: ".concat(cliente.id));
console.log("Nome: ".concat(cliente.nome));
console.log("Idade: ".concat(cliente.idade));
console.log("Codigo: ".concat(aviao.codigo));
console.log("Modelo: ".concat(aviao.modelo));
console.log("Ano: ".concat(aviao.anoLancamento));
console.log("Empresa: ".concat(aviao.empresa));
console.log("Produto: ".concat(produtoEletronico.nome));
console.log("Empresa: ".concat(produtoEletronico.empresa));
console.log("Pre\u00E7o: ".concat((produtoEletronico.preco).toFixed(2)));
funcionario.depositar(400);
